# Generated by Django 3.2.5 on 2021-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='img/Customer/', width_field=200),
        ),
    ]
