# Generated by Django 3.2.5 on 2021-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, height_field='url_height', null=True, upload_to='img/Customer/', width_field='url_width'),
        ),
    ]
