# Generated by Django 3.2.5 on 2021-07-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='width',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default=200), null=True, upload_to='img/Customer/', width_field=models.IntegerField(default=200)),
        ),
    ]
